### ISSUE TITLE
JS error in element browser (TYPO3 7.4)

### ISSUE THREAD

**Issue by fnagel** [cobwebch/linkhandler#11]
When clicking a record in the element browser following fatal error occurs:

````
Uncaught ReferenceError: link_spec is not defined
````

It seems the link_spec function fired by a onclick handler on the record is not available.

Using TYPO3 7.4.0.

**Comment by fsuter** [comment]
Keeping things working with 7.x is really hard *sigh*

Markus Klein said recently that there was a drive to integrate the linkhandler feature into 7.x. I hope it makes it before LTS freeze, because the linkhandler extension is an awful. And its a mess because that particular part of the TYPO3 CMS is one of the ugliest.

If you ever find what's wrong, you will be very welcome. I guess it's one of those old JS libraries that were removed. I will probably have to tackle that at some point, since our clients need that feature, but hopefully it makes into the Core before that. I can't promise any deadline as we haven't any plans to move clients to CMS 7 in the near future.

**Comment by fnagel** [comment]
Thanks for the fast response!

> Keeping things working with 7.x is really hard sigh
Especially if one wants to support 6.2 and 7.x -- the struggle is real ;-)

Seems the function itself has not been removed but is missing in our specific context. 
Perhaps I will find some time to dig into it, just testing a few extensions if a migration to 7.x is finally possible without too much hassle.

**Comment by fnagel** [comment]
Added a PR. Function was missing, indeed.
