### ISSUE TITLE
Upgrade to LTS 8 compatibility

### ISSUE THREAD

**Issue by haraldkrischner** [cobwebch/linkhandler#54]
Right now (correct me, if I am wrong) it is not possible to directly link to a tx_news element. Linkhandler would give that possibility I guess.

Thanks for your work

**Comment by fsuter** [comment]
Actually, you're wrong ;-) The linkhandler feature has been integrated into the Core of TYPO3 v8, so it comes out of the box. However I must say that I don't know if and where this has been documented. If you check the "What's new" slides, you should find something. Otherwise I would suggest asking in the general Slack channel.

**Comment by haraldkrischner** [comment]
In this case I am quite happy to be wrong. Thanks for your answer! And here is some documentation I found by now: https://usetypo3.com/linkhandler.html
